### PR TITLE
Add Greenwich Shepherd Clock saver

### PR DESCRIPTION
**Pull request by cormullion**
Thought some people might like this.

### CODE REVIEW

**Comment by aharris88** [comment]
It looks good, but how do you install it? It's a `.qtz` file and when I click it, it just opens up in Quicktime Player.

**Comment by cormullion** [comment]
Oh, these `.qtz` files can be moved to ~/Library/Screen Savers. If you have Quartz Composer installed, you can edit it too. (Quartz Compose is a cool but wild spaghetti-code visual programming tool installed with Apple's Developer stuff.)

**Comment by aharris88** [comment]
Ok, thanks, I just got it installed. It doesn't seem very accurate, because for some reason, the second hand doesn't line up when it comes around to 50.

But since this is the first screensaver that I've come across that is a `.qtz` file, I'm not going to merge this. I want it to be easy to install any screensaver on this list, and if I start adding `.qtz` files, I'll need to make sure to add instructions somewhere obvious, or separate the `.qtz` screen savers into a separate section with instructions. I'm not sure yet.

**Comment by cormullion** [comment]
No worries. I think installation for `.qtz` screensavers is another casualty of Apple's remorseless march into the future - but it's had a good run (10 years!). As for accuracy, well, it's a Victorian clock... :) Cheers.

**Pull request closed without merging**
